on:
  workflow_call:
    inputs:
      app_type:
        required: true
        type: string
      app_name:
        required: true
        type: string
jobs:
 docker-build-push:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Download dependencies
        run: |
          if [ "${{ inputs.app_type }}" == "java" ]; then
            mvn package
          fi
          if [ "${{ inputs.app_type }}" == "nodejs" ]; then
            npm install
          fi
          

      - name: Docker Build
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 479363499437.dkr.ecr.us-east-1.amazonaws.com
          docker build -t 479363499437.dkr.ecr.us-east-1.amazonaws.com/${{ inputs.app_name }}:${{ github.sha }} .
          docker push 479363499437.dkr.ecr.us-east-1.amazonaws.com/${{ inputs.app_name }}:${{ github.sha }}


# Python and nodejs will not have any thing to at build phase so we will not create any build job for them. We will create only test and deploy jobs for them.
  # nodejs:
  #   runs-on: self-hosted 
    # if: inputs.app_type == 'nodejs'
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Run a one-line script
  #       run: echo Hello, world!   
  
  # python:
  #   runs-on: self-hosted
  #   if: inputs.app_type  == 'python'
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Run a one-line script
  #       run: echo Hello, world!