on:
  workflow_call:
    inputs:
      app_type:
        required: true
        type: string

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      app_type: nodejs

  test:
    runs-on: self-hosted
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, world!

  dev-deploy:
    runs-on: self-hosted
    needs: test
    environment: dev
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, world!

  qa-deploy:
    runs-on: self-hosted
    needs: dev-deploy
    environment: qa
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, world!
        
  uat-deploy:
    runs-on: self-hosted
    needs: qa-deploy
    environment: uat
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, world!
  Prod-deploy:
    runs-on: self-hosted
    needs: uat-deploy
    environment: prod
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, world!