on:
  workflow_call:
    inputs:
      app_type:
        required: true
        type: string

jobs:
  

  test:
    uses: satyamdevops09/roboshop-github-actions/.github/workflows/unittest.yml@main
   
    with:
      app_type: ${{ inputs.app_type }}

  build:
    uses: satyamdevops09/roboshop-github-actions/.github/workflows/build.yml@main
    needs: test
    with:
      app_type: ${{ inputs.app_type }}

  
 
  dev-deploy:
    runs-on: self-hosted
    needs: test
    environment: dev
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, world!

  qa-deploy:
    runs-on: self-hosted
    needs: dev-deploy
    environment: qa
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, world!
        
  uat-deploy:
    runs-on: self-hosted
    needs: qa-deploy
    environment: uat
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, world!
  Prod-deploy:
    runs-on: self-hosted
    needs: uat-deploy
    environment: prod
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, world!